# Generated by Django 3.0.7 on 2020-07-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChamaMembers',
            fields=[
                ('memberID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('secondName', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Chamas',
            fields=[
                ('chamaID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('chamaName', models.CharField(max_length=50)),
                ('subscription', models.CharField(max_length=5)),
                ('regDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='fieldID',
            fields=[
                ('fieldName', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('currentNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=20)),
                ('transactionType', models.CharField(max_length=30)),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ChamaMembers')),
            ],
        ),
        migrations.AddField(
            model_name='chamamembers',
            name='chamaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Chamas'),
        ),
    ]
