# Generated by Django 3.0.7 on 2020-09-09 03:35

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamaMembers',
            fields=[
                ('memberID', models.CharField(default=dashboard.models.generate_memberID, max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chamas',
            fields=[
                ('chamaID', models.CharField(default=dashboard.models.generate_ChamaID, max_length=15, primary_key=True, serialize=False)),
                ('chamaName', models.CharField(max_length=50)),
                ('regDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fieldID',
            fields=[
                ('fieldName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('currentNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LoanStatus',
            fields=[
                ('loanStatusID', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionTypes',
            fields=[
                ('subscriptionType', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTypes',
            fields=[
                ('transactionType', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoanSettings',
            fields=[
                ('chamaID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.Chamas')),
                ('interestRate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('repaymentPeriod', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactionID', models.CharField(default=dashboard.models.generate_TransactionID, max_length=20, primary_key=True, serialize=False)),
                ('transactionDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0)),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ChamaMembers')),
                ('transactionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TransactionTypes')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('subscriptionID', models.CharField(default=dashboard.models.generate_SubscriptionID, max_length=20, primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(default=dashboard.models.set_Transaction_Expiry)),
                ('amount', models.IntegerField(default=0)),
                ('chamaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Chamas')),
                ('subscriptionType', models.ForeignKey(default='trial', on_delete=django.db.models.deletion.CASCADE, to='dashboard.SubscriptionTypes')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loanID', models.CharField(default=dashboard.models.generate_loanID, max_length=30, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('repaymentAmount', models.IntegerField(default=models.IntegerField(default=0))),
                ('issueDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('repaymentDate', models.DateTimeField(default=dashboard.models.set_Repayment_Date)),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ChamaMembers')),
                ('status', models.ForeignKey(default='unpaid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.LoanStatus')),
            ],
        ),
        migrations.AddField(
            model_name='chamamembers',
            name='chamaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Chamas'),
        ),
        migrations.AddField(
            model_name='chamamembers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
