# Generated by Django 3.0.7 on 2020-08-12 00:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Amount must be greater than 0')]),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 0, 42, 52, 604054)),
        ),
    ]
