# Generated by Django 3.0.7 on 2020-07-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='id',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transactionID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
