# Generated by Django 3.0.7 on 2020-07-22 17:27

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200722_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamas',
            name='chamaID',
            field=models.CharField(default=dashboard.models.generate_ChamaID, max_length=15, primary_key=True, serialize=False),
        ),
    ]
