# Generated by Django 3.0.7 on 2020-08-12 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200812_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 1, 18, 33, 558525)),
        ),
    ]
