# Generated by Django 3.0.7 on 2020-08-13 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200812_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='amount',
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 14, 6, 19, 493509)),
        ),
    ]
