# Generated by Django 3.0.7 on 2020-07-24 03:49

import dashboard.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200722_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTypes',
            fields=[
                ('transactionType', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='transactionType',
        ),
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transactionDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chamamembers',
            name='memberID',
            field=models.CharField(default=dashboard.models.generate_memberID, max_length=15, primary_key=True, serialize=False),
        ),
    ]
