# Generated by Django 3.0.7 on 2020-08-22 21:57

import dashboard.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200813_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamas',
            name='regDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='endDate',
            field=models.DateTimeField(default=dashboard.models.set_Transaction_Expiry),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transactionDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
