# Generated by Django 3.0.7 on 2020-07-24 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200724_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transactionType',
            field=models.ForeignKey(default='merry-go-round', on_delete=django.db.models.deletion.CASCADE, to='dashboard.TransactionTypes'),
            preserve_default=False,
        ),
    ]
