# Generated by Django 3.0.7 on 2020-07-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_transactions_transactiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamas',
            name='funds',
            field=models.IntegerField(default=0),
        ),
    ]
