# Generated by Django 3.0.7 on 2020-07-29 02:30

import dashboard.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_chamas_funds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTypes',
            fields=[
                ('subscriptionType', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='chamas',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='chamamembers',
            name='status',
            field=models.CharField(default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='fieldid',
            name='fieldName',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('subscriptionID', models.CharField(default=dashboard.models.generate_SubscriptionID, max_length=20, primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(default=datetime.datetime(2020, 8, 28, 2, 30, 1, 782188))),
                ('amount', models.IntegerField(default=0)),
                ('chamaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Chamas')),
                ('subscriptionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SubscriptionTypes')),
            ],
        ),
    ]
