# Generated by Django 3.0.7 on 2020-09-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_loans_loanstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSettings',
            fields=[
                ('chamaID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.Chamas')),
                ('interestRate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('repaymentPeriod', models.IntegerField(default=0)),
            ],
        ),
    ]
