# Generated by Django 3.0.7 on 2020-07-29 03:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200729_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 3, 39, 15, 583711)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='subscriptionType',
            field=models.ForeignKey(default='trial', on_delete=django.db.models.deletion.CASCADE, to='dashboard.SubscriptionTypes'),
        ),
    ]
