# Generated by Django 3.0.7 on 2020-09-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200908_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='repaymentAmount',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
    ]
