# Generated by Django 3.0.7 on 2020-07-29 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200729_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamas',
            name='chamaName',
            field=models.CharField(default='CHAMA SMART GROUP', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 4, 48, 19, 260692)),
        ),
    ]
