# Generated by Django 3.0.7 on 2020-08-01 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200729_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 22, 51, 29, 891947)),
        ),
    ]
