# Generated by Django 3.0.7 on 2020-09-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_loans_repaymentamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansettings',
            name='repaymentPeriod',
            field=models.IntegerField(default=30),
        ),
    ]
