# Generated by Django 3.0.7 on 2020-08-01 23:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_auto_20200801_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamas',
            name='user',
            field=models.OneToOneField(default=35, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 23, 0, 26, 872411)),
        ),
    ]
