# Generated by Django 3.0.7 on 2020-08-02 02:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200801_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='chamaID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Chamas'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 2, 5, 17, 773985)),
        ),
    ]
